#+TITLE: Jackson de Jesus
#+LANGUAGE: pt-br
#+DESCRIPTION: Site pessoal
#+AUTHOR: Jackson de Jesus
#+EXPORT_FILE_NAME: index.html
#+OPTIONS: author:nil html-postamble:nil toc:nil num:nil html5-fancy:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://cdn.simplecss.org/simple.min.css">

* Início...

- 👋 Oi, me chamo Jackson,
- 👀 curto tecnologia e linguagens (nas suas diversas modalidades),
- 🌱 estudo muitos temas, dentre os quais, ciência de dados,
- 💞️ gosto de Software Livre e sistemas Unix-like,
- 📫 ainda prefiro usar o e-mail (não uso nenhuma rede social),
- ⚡ converso sozinho no [[https://jackson.jesus.nom.br][sitezinho...]]

** Notas de aulas (versão Emacs)...

Algumas anotações pessoais das disciplinas que estudo no curso Ciência de dados, sob a liceça [[https://creativecommons.org/licenses/by-sa/4.0/deed.pt_BR][Creative Commons]] (sempre em revisão)...

[[./estatistica.html][(a) Estatística]],
[[./banco-dados.html][(b) Banco de dados]],
[[./ia.html][(c) Inteligência artificial]],
[[./python.html][(d) Python,]]
[[./sgbd.html][(e) SGBD]],
[[./engenharia-software.html][(f) Engenharia de software]],
[[./lec.html][(g) Legislação, ética e conformidade (versão antiga com emacs)]],

** Notas de aulas (versão Vimwiki).

Inicialmente, como descrito nas observações no final das páginas acima, usei o NotebookLM (IA Generativa específica) para organizar tabelas no formato Markdown com o resumo dos principais conceitos de cada capítulo dos textos estudados; e ia revisando aos poucos.

Mas a partir de hoje (26.06.2024), passo a usar o Vimwiki como editor e gerador das páginas deste site, por motivos de simplicidade. O Vimwiki me parece a versão /Org Mode/ do Emacs, por isso curti muito. Só troquei o CSS padrão dele por outro que exibe os conceitos das tabelas como /flash cards/, algo bem apropriado para um site de revisão de estudos.

Ah, as notas anteriores ainda são válidas como registro (e ainda tenho a pretensão de revisá-las manualmente).

[[./legislacao.html][(g) Legislação, ética e conformidade (versão atual com vimwiki)]]...

Os códigos deste site estão [[https://github.com/jackson-ufpe/jackson-ufpe.github.io][neste repositório.]]

[[https://jeffhuang.com/designed_to_last][Este site foi projetado para durar.]]
