#+TITLE: 
#+LANGUAGE: pt-br
#+DESCRIPTION: Resumo dos conceitos de 
#+AUTHOR: Jackson de Jesus
#+EXPORT_FILE_NAME: .html
#+OPTIONS: num:nil html5-fancy:t
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

** Capítulo 1

** Capítulo 2

** Capítulo 3

** Capítulo 4

** Capítulo 5

** Capítulo 6

** Observações...

*** Como organizei o conteúdo desta página

Esta página contém resumos dos principais conceitos da disciplina sistema gerenciador de banco de dados, extraídos de arquivos no formato PDF com a ferramenta [[https://notebooklm.google.com][NotebookLM]].

De forma simples, enviei os arquivos para o NotebookLM e pedi os resumos com os seguintes comandos:

*Organize uma tabela com os principais conceitos do texto. Na primeira coluna, o nome do conceito e na segunda, o conceito em si.*

A partir do segundo pedido, usei o comando:

*Repita o processo anterior para este texto.*

No terceiro pedido, recebi a mensage de:

*O comando fornecido solicita que o processo anterior seja repetido. No entanto, não há processo anterior no histórico de conversas fornecido. [Me] Para obter uma resposta abrangente, forneça o processo anterior que você gostaria que fosse repetido.*

Desta forma, alternei entre o primeiro e segundo comando até o último arquivo, que veio com a formatação Markdown deformada. Então, pedi uma última revisão com o comando:

*Refaça a tabela para uma melhor formatação em Markdown.*

A publicação final continua uma exportação simples, do formato org mode para HTML, usando o Emacs.

* [[./index.html][Voltar para o início...]]
